spring.application.name=CoffeBackend
spring.datasource.url=jdbc:mysql://localhost:3306/cavoshcafe
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true